# Generated by Django 5.1 on 2025-02-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blog_content_blog_created_at_blog_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_social_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
